"""empty message

Revision ID: 889db9b7991d
Revises: fc35d8e97d51
Create Date: 2023-10-31 15:51:44.436233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889db9b7991d'
down_revision = 'fc35d8e97d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
